name 'cesnet-site_hadoop'
version '1.1.1'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-site_hadoop'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'Hadoop Site-Specific Module'
description 'Hadoop Site-Specific Module'
project_page 'https://github.com/MetaCenterCloudPuppet/cesnet-site_hadoop'

dependency 'puppetlabs/stdlib', '>= 1.0.0 <5.0.0'
