name          'meta-size_hadoop'
version       '0.1.0'
source        'mailto://valtri@civ.zcu.cz'
author        'CESNET'
license       'Public Domain'
summary       'Hadoop Site-Specific Stuff'
description   'Site-specific setup for Hadoop Cluster'
project_page  'https://github.com/CESNET/'

dependency 'puppetlabs/stdlib'
